add_noise: true
aggregation: mean
attack_probability: 1.0
attack_scale: 10
attack_type: direction
baseGlobal: false
batch_size: 256
cat_policy: indices
contrastive_loss: true
cosine_similarity: false
dataset: blog
device: !!python/object/apply:torch.device
- cpu
dims:
- 26
- 256
- 256
distance_loss: true
dropout_rate: 0.2
epochs: 1
flOnly: true
fl_cluster: 4
framework: blog
isBatchNorm: false
isDropout: false
learning_rate: 0.001
learning_rate_reducer: 0.001
local: false
masking_ratio: 0.3
mlflow: false
modeFL: false
model_config: blog
model_mode: ae
n_classes: 2
n_subsets: 2
noise_level: 0.3
noise_std: 0.1
noise_type: swap_noise
norm: l1
normalize: false
nth_epoch: 1
overlap: 0
p_norm: 2
paths:
  data: ../data/
  results: ./results/
poison: true
poisonClient: 0.3
poisonLevel: 1
profile: false
randomClient: true
randomLevel: 0.5
randomSelection: false
reconstruct_subset: false
reconstruction: true
sampling: 1
scheduler: false
seed: 57
shallow_architecture: false
target_layer: encoder.layer1
task_type: binclass
tau: 0.1
training_data_ratio: 0.2
validate: false
